'use strict'

export const Types = {
    UPDATE_PRODUCT:'UPDATE_PRODUCT',
    ADD_PRODUCT_BID: 'ADD_PRODUCT_BID',
    UPDATE_PRODUCTS:'UPDATE_PRODUCTS',
    UPDATE_USER_PRODUCTS: 'UPDATE_USER_PRODUCTS',
    UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
    UPDATE_NAME:'UPDATE_NAME',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_QUERY: 'UPDATE_QUERY'
};

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};